round

In [1]:
#rounding / formatting
round(1.25361,3)

1.254

In [3]:
x = 1.23456
format(x, '0.3f')

'1.235'

In [6]:
#Warning!!!!!!!!!!!!!
a = 2.1
b = 4.2
c = a + b
print(c)
(a+b)==6.3

6.300000000000001


False

In [9]:
#use decimal module
from decimal import Decimal
a = Decimal('4.2')
b = Decimal('2.1')
a + b
print(a + b)
(a + b) == Decimal('6.3')

6.3


True

In [18]:
import numpy as np
a = np.array([2+3j, 4+5j, 6-7j, 8+9j])
print(a)
print(a+2) #!! n'affecte pas la valeur ici 
print(a)

[2.+3.j 4.+5.j 6.-7.j 8.+9.j]
[ 4.+3.j  6.+5.j  8.-7.j 10.+9.j]
[2.+3.j 4.+5.j 6.-7.j 8.+9.j]


In [23]:
#Fraction
from fractions import Fraction
a = Fraction(5, 4)
b = Fraction(7, 16)
print(a + b)
print(a.numerator)
print(float(a))
print(a)

27/16
5
1.25
5/4


In [30]:
x = [1, 2, 3, 4]
y = [5, 6, 7, 8]
print(x*2)
# x+2 ne marche pas => Il faut utiliser Numpy lib

import numpy as np
ax = np.array([1, 2, 3, 4])
ay = np.array([5, 6, 7, 8])
print(ax * 2)
print(ax+2)

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]
[3 4 5 6]


In [34]:
 def f(x):
    return 3*x
print(ax)
f(ax)

[1 2 3 4]


array([ 3,  6,  9, 12])